include:

- board: nice_nano//zmk
  shield: corne_left

- board: nice_nano//zmk
  shield: corne_right
  cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y -DCONFIG_LV_FONT_UNSCII_8=y

- board: nice_nano//zmk
  shield: settings_reset
